#!/usr/bin/env bash

src=${PWD}
alacritty_dest=$HOME/.config/alacritty
bin_dst=$HOME/.local/bin
fish_dst=$HOME/.config/fish
mpv_dst=$HOME/.config/mpv
neovim_dst=$HOME/.config/nvim
neovim_backup=$HOME/.local/share/nvim
vifm_dst=$HOME/.config/vifm

delete_all() {
  for file in "$alacritty_dest" "$fish_dst" "$mpv_dst" "$neovim_dst" \
    "$vifm_dst" "$HOME"/.{bashrc,bash_profile,gitconfig,tmux.conf}; do
    [[ -e $file ]] && rm -rf "$file"
  done
  printf "%s\n" "dotfiles deleted."
}

install_alacritty_configs() {
  if type -p alacritty &>/dev/null; then
    mkdir -p "$alacritty_dest"
    ln -sfv "$src"/alacritty/alacritty.yml "$alacritty_dest"
  fi
}

install_fish_configs() {
  if type -p fish &>/dev/null; then
    mkdir -p "$fish_dst"/{conf.d,functions}
    ln -sfv "$src"/fish/config.fish "$fish_dst"
  fi
}

install_mpv_configs() {
  if type -p mpv &>/dev/null; then
    mkdir -p "$mpv_dst"
    for file in "$src"/mpv/*; do
      cp -fv "$file" "$mpv_dst"
    done
  fi
}

install_neovim_configs() {
  mkdir -p "$neovim_dst"/colors
  mkdir -p "$neovim_backup"/{backup,undo}
  ln -sfv "$src"/nvim/init.vim "$neovim_dst"
  for file in "$src"/nvim/colors/*; do
    cp -fv "$file" "$neovim_dst"/colors
  done
}

install_vifm_configs() {
  mkdir -p "$vifm_dst"/colors
  cp -fv "$src"/vifm/colors/* "$vifm_dst"/colors
  ln -sfv "$src"/vifm/vifmrc "$vifm_dst"/vifmrc
}

install_user_scripts() {
  mkdir -p "$bin_dst"
  for file in "$src"/bin/*; do
    cp -fv "$file" "$bin_dst"
  done
  chmod 700 "$bin_dst"/*
}

install_home_configs() {
  for file in bashrc bash_profile tmux.conf; do
    ln -sfv "$src"/home/"$file" "$HOME"/."$file"
  done
  cp -fv "$src"/home/gitconfig "$HOME"/.gitconfig
  chmod 600 "$HOME"/.gitconfig
}

main() {
  mkdir -p "$HOME"/projects/tmp
  install_alacritty_configs
  install_fish_configs
  install_mpv_configs
  install_neovim_configs
  install_vifm_configs
  install_user_scripts
  install_home_configs
}

while [[ ! $# -eq 0 ]]; do
  case "$1" in
    --delete | -d)
      delete_all
      exit
      ;;
  esac
  shift
done

main "$@"

